INSERT INTO USER (ID, USERID, USERNAME, PASSWORD, NICKNAME, CONTACT, EMAIL, ACTIVATED) VALUES (1, 'admin', 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', '010-0000-0000', 'admin@example.com', 1);
INSERT INTO USER (ID, USERID, USERNAME, PASSWORD, NICKNAME, CONTACT, EMAIL, ACTIVATED) VALUES (2, 'user', 'user', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'user', '010-0000-0000', 'user@example.com', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (ID, AUTHORITY_NAME) values (2, 'ROLE_USER');
